#include "DataExporter.h"

#include <QFile>
#include <QTextStream>
#include <QDateTime>
#include <QDebug>

// nlohmann/json (single-header, place json.hpp in third_party/)
#include "json.hpp"
using json = nlohmann::json;

// ── Public dispatch ───────────────────────────────────────────────────────────
bool DataExporter::exportFrames(const std::vector<ScanFrame>& frames,
                                const QString& path, Format format) {
    switch (format) {
        case Format::CSV:    return writeCsv(frames, path);
        case Format::PCD:    return writePcd(frames, path);
        case Format::PLY:    return writePly(frames, path);
        case Format::JSON:   return writeJson(frames, path);
        case Format::ROSBag: return writeRosBag(frames, path);
    }
    return false;
}

bool DataExporter::exportFrame(const ScanFrame& frame,
                               const QString& path, Format format) {
    return exportFrames({frame}, path, format);
}

// ── Filename helpers ──────────────────────────────────────────────────────────
QString DataExporter::extension(Format format) {
    switch (format) {
        case Format::CSV:    return "csv";
        case Format::PCD:    return "pcd";
        case Format::PLY:    return "ply";
        case Format::JSON:   return "json";
        case Format::ROSBag: return "mcap";
    }
    return "bin";
}

QString DataExporter::suggestFilename(Format format) {
    QString ts = QDateTime::currentDateTime().toString("yyyyMMdd_HHmmss");
    return QString("rplidar_%1.%2").arg(ts, extension(format));
}

// ── CSV ───────────────────────────────────────────────────────────────────────
// Columns: frame, angle_deg, distance_mm, quality, x_mm, y_mm
bool DataExporter::writeCsv(const std::vector<ScanFrame>& frames,
                             const QString& path) {
    QFile f(path);
    if (!f.open(QIODevice::WriteOnly | QIODevice::Text)) {
        m_lastError = f.errorString();
        return false;
    }
    QTextStream s(&f);
    s << "frame,angle_deg,distance_mm,quality,x_mm,y_mm\n";

    for (std::size_t fi = 0; fi < frames.size(); ++fi) {
        for (const auto& pt : frames[fi]) {
            s << fi << ","
              << QString::number(pt.angle_deg,   'f', 3) << ","
              << QString::number(pt.distance_mm, 'f', 2) << ","
              << pt.quality << ","
              << QString::number(pt.x(), 'f', 2) << ","
              << QString::number(pt.y(), 'f', 2) << "\n";
        }
    }
    return true;
}

// ── PCD (ASCII v0.7) ──────────────────────────────────────────────────────────
// Compatible with PCL, ROS, CloudCompare.
bool DataExporter::writePcd(const std::vector<ScanFrame>& frames,
                             const QString& path) {
    // Count valid points
    std::size_t total = 0;
    for (const auto& fr : frames)
        for (const auto& pt : fr)
            if (pt.isValid()) ++total;

    QFile f(path);
    if (!f.open(QIODevice::WriteOnly | QIODevice::Text)) {
        m_lastError = f.errorString();
        return false;
    }
    QTextStream s(&f);

    // PCD header
    s << "# Generated by RPLidarGUI\n"
      << "VERSION 0.7\n"
      << "FIELDS x y z intensity\n"
      << "SIZE 4 4 4 4\n"
      << "TYPE F F F F\n"
      << "COUNT 1 1 1 1\n"
      << "WIDTH "  << total << "\n"
      << "HEIGHT 1\n"
      << "VIEWPOINT 0 0 0 1 0 0 0\n"
      << "POINTS " << total << "\n"
      << "DATA ascii\n";

    // Data rows: x y z(=0 for 2-D lidar) intensity(quality)
    for (const auto& fr : frames) {
        for (const auto& pt : fr) {
            if (!pt.isValid()) continue;
            // Convert mm → m (PCL convention)
            s << QString::number(pt.x() / 1000.0f, 'f', 6) << " "
              << QString::number(pt.y() / 1000.0f, 'f', 6) << " "
              << "0.000000 "
              << pt.quality << "\n";
        }
    }
    return true;
}

// ── PLY (ASCII) ───────────────────────────────────────────────────────────────
// Opens in MeshLab, CloudCompare, Blender.
bool DataExporter::writePly(const std::vector<ScanFrame>& frames,
                             const QString& path) {
    std::size_t total = 0;
    for (const auto& fr : frames)
        for (const auto& pt : fr)
            if (pt.isValid()) ++total;

    QFile f(path);
    if (!f.open(QIODevice::WriteOnly | QIODevice::Text)) {
        m_lastError = f.errorString();
        return false;
    }
    QTextStream s(&f);

    s << "ply\n"
      << "format ascii 1.0\n"
      << "comment Generated by RPLidarGUI\n"
      << "element vertex " << total << "\n"
      << "property float x\n"
      << "property float y\n"
      << "property float z\n"
      << "property uchar intensity\n"
      << "end_header\n";

    for (const auto& fr : frames) {
        for (const auto& pt : fr) {
            if (!pt.isValid()) continue;
            s << QString::number(pt.x() / 1000.0f, 'f', 6) << " "
              << QString::number(pt.y() / 1000.0f, 'f', 6) << " "
              << "0.000000 "
              << pt.quality << "\n";
        }
    }
    return true;
}

// ── JSON ──────────────────────────────────────────────────────────────────────
// Array of frames, each frame is an array of point objects.
bool DataExporter::writeJson(const std::vector<ScanFrame>& frames,
                              const QString& path) {
    json root = json::array();

    for (std::size_t fi = 0; fi < frames.size(); ++fi) {
        json frameObj;
        frameObj["frame"] = fi;
        frameObj["points"] = json::array();

        for (const auto& pt : frames[fi]) {
            root.push_back({
                {"frame",       fi},
                {"angle_deg",   std::round(pt.angle_deg   * 1000) / 1000},
                {"distance_mm", std::round(pt.distance_mm * 100)  / 100},
                {"quality",     pt.quality},
                {"x_mm",        std::round(pt.x() * 100)  / 100},
                {"y_mm",        std::round(pt.y() * 100)  / 100}
            });
        }
    }

    QFile f(path);
    if (!f.open(QIODevice::WriteOnly | QIODevice::Text)) {
        m_lastError = f.errorString();
        return false;
    }
    QTextStream s(&f);
    s << QString::fromStdString(root.dump(2));
    return true;
}

// ── ROS bag (MCAP-style, CSV-inside for simplicity) ───────────────────────────
// A real ROS2 MCAP bag needs the mcap C++ library.  Here we emit a
// self-describing CSV wrapped in a minimal MCAP-compatible text header so
// the file can be post-processed with the mcap CLI or converted to a real bag.
// Replace with the official mcap library for full ROS2 compatibility.
bool DataExporter::writeRosBag(const std::vector<ScanFrame>& frames,
                                const QString& path) {
    QFile f(path);
    if (!f.open(QIODevice::WriteOnly | QIODevice::Text)) {
        m_lastError = f.errorString();
        return false;
    }
    QTextStream s(&f);

    // Minimal MCAP-like text header
    s << "# MCAP-compatible CSV export — RPLidarGUI\n";
    s << "# topic: /scan  type: sensor_msgs/LaserScan\n";
    s << "# timestamp_ns,frame,angle_deg,distance_mm,quality\n";

    qint64 baseNs = QDateTime::currentMSecsSinceEpoch() * 1'000'000LL;
    for (std::size_t fi = 0; fi < frames.size(); ++fi) {
        qint64 ts = baseNs + static_cast<qint64>(fi) * 100'000'000LL; // 100ms apart
        for (const auto& pt : frames[fi]) {
            s << ts << ","
              << fi << ","
              << QString::number(pt.angle_deg,   'f', 3) << ","
              << QString::number(pt.distance_mm, 'f', 2) << ","
              << pt.quality << "\n";
        }
    }
    return true;
}
